import esbuild from "esbuild";
import process from "process";
import builtins from 'builtin-modules';
import { copyFileSync, mkdirSync } from 'fs';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

const buildOptions = {
	banner: {
		js: banner,
	},
	entryPoints: ['main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/closebrackets',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/comment',
		'@codemirror/fold',
		'@codemirror/gutter',
		'@codemirror/highlight',
		'@codemirror/history',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/matchbrackets',
		'@codemirror/panel',
		'@codemirror/rangeset',
		'@codemirror/rectangular-selection',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/stream-parser',
		'@codemirror/text',
		'@codemirror/tooltip',
		'@codemirror/view',
		...builtins],
	format: 'cjs',
	target: 'es2016',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'build/main.js',
};

if (prod) {
	// Create build directory if it doesn't exist
	mkdirSync('build', { recursive: true });

	esbuild.build(buildOptions).then(() => {
		// Copy additional files to build directory
		copyFileSync('manifest.json', 'build/manifest.json');
		copyFileSync('styles.css', 'build/styles.css');
		console.log('✓ Build complete - files copied to build/');
	}).catch(() => process.exit(1));
} else {
	esbuild.context(buildOptions).then(ctx => ctx.watch()).catch(() => process.exit(1));
}
